FROM alpine:3.16.1
USER root

# ref: https://github.com/Zenika/alpine-chrome
RUN apk add --upgrade --no-cache chromium ttf-freefont font-noto-emoji nodejs yarn && \
    apk add wqy-zenhei --update-cache --repository=https://nl.alpinelinux.org/alpine/edge/testing --allow-untrusted && \
    rm -rf /var/cache/* && \
    mkdir /var/cache/apk

ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_PATH=/usr/lib/chromium/
ENV PUPPETEER_EXECUTABLE_PATH="${CHROMIUM_BIN}"
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH="${CHROMIUM_BIN}"
ENV PLAYWRIGHT_BROWSERS_PATH="${CHROME_PATH}"
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

COPY ./ /opt
WORKDIR /opt

RUN yarn install --production=false && \
    yarn build && \
    yarn cache clean && \
    yarn install --production=true

CMD yarn start